name: Matrix & Strategy
on: [workflow_dispatch]
jobs:
  Matrix:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 12
            operating-system: ubuntu-latest
        exclude:
          - node-version: 20
            operating-system: windows-latest
          - node-version: 18
            operating-system: windows-latest        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build