name: Reusable workflow example
on: 
  workflow_call:    
    inputs:
      dist-files:
        required: true
        default: dist-files
        type: string                                                                                                    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.dist-files}}
      - name: List files
        run: ls